export const PHASE3_WORDS = [
  { hindi: "मौत", english: ["death"], category: "Cinderella · Lesson 1a" },
  { hindi: "शादी", english: ["wedding", "marriage"], category: "Cinderella · Lesson 1a" },
  { hindi: "सौतेली / सौतेला", english: ["stepmother / stepfather", "stepparent"], category: "Cinderella · Lesson 1a" },
  { hindi: "तंग करना", english: ["to annoy", "to bother", "to trouble"], category: "Cinderella · Lesson 1a" },
  { hindi: "अकेले", english: ["alone", "by oneself"], category: "Cinderella · Lesson 1a" },
  { hindi: "फटे-पुराने", english: ["tattered", "worn-out", "ragged"], category: "Cinderella · Lesson 1a" },
  { hindi: "परी", english: ["fairy"], category: "Cinderella · Lesson 1a" },
  { hindi: "बग्गी", english: ["carriage", "buggy", "coach"], category: "Cinderella · Lesson 1a" },
  { hindi: "तक", english: ["until", "up to"], category: "Cinderella · Lesson 1a" },
  { hindi: "गायब होना", english: ["to disappear", "to vanish"], category: "Cinderella · Lesson 1a" },
  { hindi: "राजकुमार", english: ["prince"], category: "Cinderella · Lesson 1a" },
  { hindi: "हर", english: ["every", "each"], category: "Cinderella · Lesson 1a" },
  { hindi: "जलपरी", english: ["mermaid"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "इंसान", english: ["human", "person"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "शौक", english: ["hobby", "interest", "passion"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "समुद्र", english: ["sea", "ocean"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "डूबना", english: ["to drown", "to sink"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "होश में लाना", english: ["to revive", "to bring someone round"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "गाना", english: ["to sing"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "जादूगरनी", english: ["witch", "sorceress"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "मौक़ा", english: ["opportunity", "chance"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "फ़ायदा", english: ["benefit", "advantage", "use"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "शर्त", english: ["condition", "term"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "सरकार", english: ["government"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "मानना", english: ["to accept", "to agree", "to believe"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "क़ैद करना", english: ["to imprison", "to capture"], category: "The Little Mermaid · Lesson 2a" },
  { hindi: "पहचानना", english: ["to recognise", "to recognize"], category: "The Little Mermaid · Lesson 3a" },
  { hindi: "पाता", english: ["finds", "is able to find"], category: "The Little Mermaid · Lesson 3a" },
  { hindi: "दिमाग़", english: ["brain", "mind"], category: "The Little Mermaid · Lesson 3a" },
  { hindi: "दीमक", english: ["termite"], category: "The Little Mermaid · Lesson 3a" },
  { hindi: "जान बचाना", english: ["to save a life", "to save someone's life"], category: "The Little Mermaid · Lesson 3a" },
  { hindi: "रूप बदलना", english: ["to change one's appearance", "to transform"], category: "The Little Mermaid · Lesson 4a" },
  { hindi: "मिलाना", english: ["to match", "to mix", "to bring together"], category: "The Little Mermaid · Lesson 4a" },
  { hindi: "तय कर देना / तय करना", english: ["to decide", "to settle"], category: "The Little Mermaid · Lesson 4a" },
  { hindi: "पता चलना", english: ["to find out", "to discover"], category: "The Little Mermaid · Lesson 4a" },
  { hindi: "मंगनी", english: ["engagement"], category: "The Little Mermaid · Lesson 4a" },
  { hindi: "गला", english: ["throat", "neck"], category: "The Little Mermaid · Lesson 4a" },
  { hindi: "छीनना", english: ["to snatch", "to take away"], category: "The Little Mermaid · Lesson 4a" },
  { hindi: "सौदा करना", english: ["to make a deal", "to bargain"], category: "The Little Mermaid · Lesson 4a" },
  { hindi: "हथियार", english: ["weapon"], category: "The Little Mermaid · Lesson 4a" }
];
